# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.1
        environment:
        - PG_HOST=localhost
        - PG_USER=postgres
        - NODE_ENV=test
      - image: circleci/postgres:9.6.2-alpine
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=plutonium-test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: sudo apt-get update -qq && sudo apt-get install -y build-essential postgresql

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: run tests with coverage
          command: yarn coverage
          environment:
          - DATABASE_URL: "postgres://postgres@localhost:5432/plutonium-test"

      - store_artifacts:
          path: ./coverage
          destination: /coverage

      - run:
          name: report coverage to coveralls
          command: yarn coveralls

