# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
        environment:
        - PG_HOST=localhost
        - PG_USER=ubuntu
        - NODE_END=test
      - image: circleci/postgres:9.6.2-alpine
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=cpro-test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y build-essential postgresql

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: createdb cpro-test
      # run tests!
      - run:
          name: run tests
          command: yarn test
        environment:
          - DATABASE_URL: "postgres://ubuntu@localhost:5432/cpro-test"


